services:
  dev: 
    image: mcr.microsoft.com/devcontainers/go:1.25-bookworm
    volumes:
      - ../:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: redis
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 5s
        timeout: 2s
        retries: 5